## Linear Models

***

## Project Description

Load the Lahman library. The Teams data frame contains an attendance column. This is the total attendance for the season. To calculate average attendance, divide by the number of games played, as follows: Use linear models to answer the following 3-part question about Teams_small.

### Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import statsmodels.api as sm
from statsmodels.formula.api import ols

import datetime
from datetime import datetime, timedelta

import scipy.stats

import pandas_profiling
from pandas_profiling import ProfileReport


%matplotlib inline
#sets the default autosave frequency in seconds
%autosave 60 
sns.set_style('dark')
sns.set(font_scale=1.2)

plt.rc('axes', titlesize=9)
plt.rc('axes', labelsize=14)
plt.rc('xtick', labelsize=12)
plt.rc('ytick', labelsize=12)

import warnings
warnings.filterwarnings('ignore')

# Use Folium library to plot values on a map.
#import folium

# Use Feature-Engine library
#import feature_engine
#import feature_engine.missing_data_imputers as mdi
#from feature_engine.outlier_removers import Winsorizer
#from feature_engine import categorical_encoders as ce
#from feature_engine.discretisation import EqualWidthDiscretiser, EqualFrequencyDiscretiser, DecisionTreeDiscretiser
#from feature_engine.encoding import OrdinalEncoder

pd.set_option('display.max_columns',None)
#pd.set_option('display.max_rows',None)
pd.set_option('display.width', 1000)
pd.set_option('display.float_format','{:.2f}'.format)

np.random.seed(0)
np.set_printoptions(suppress=True)

Autosaving every 60 seconds

In [2]:
df = pd.read_csv("teamssmall.csv")

In [3]:
df

      yearID lgID teamID franchID divID  Rank    G  Ghome   W    L DivWin WCWin LgWin WSWin    R    AB     H  X2B  X3B   HR   BB    SO   SB  CS   HBP    SF   RA   ER  ERA  CG  SHO  SV  IPouts    HA  HRA  BBA   SOA    E   DP   FP                  name                       park  attendance  BPF  PPF teamIDBR teamIDlahman45 teamIDretro  avg_attendance
0       1961   AL    BAL      BAL   NaN     3  163     82  95   67    NaN   NaN     N     N  691  5481  1393  227   36  149  581   902   39  30   nan   nan  588  526 3.22  54   21  33    4413  1226  109  617   926  126  173 0.98     Baltimore Orioles           Memorial Stadium      951089   96   96      BAL            BAL         BAL         5834.90
1       1961   AL    BOS      BOS   NaN     6  163     82  76   86    NaN   NaN     N     N  729  5508  1401  251   37  112  647   847   56  36   nan   nan  792  687 4.29  35    6  30    4326  1472  167  679   831  143  140 0.98        Boston Red Sox             Fenway Park II      850589  102  103      BOS            BOS         BOS         5218.34
2       1961   AL    CHA      CHW   NaN     4  163     81  86   76    NaN   NaN     N     N  765  5556  1475  216   46  138  550   612  100  40   nan   nan  726  653 4.06  39    3  33    4344  1491  158  498   814  128  138 0.98     Chicago White Sox              Comiskey Park     1146019   99   97      CHW            CHA         CHA         7030.79
3       1961   NL    CHN      CHC   NaN     7  156     78  64   90    NaN   NaN     N     N  689  5344  1364  238   51  176  539  1027   35  25   nan   nan  800  689 4.48  34    6  25    4155  1492  165  465   755  183  175 0.97          Chicago Cubs              Wrigley Field      673057  101  104      CHC            CHN         CHN         4314.47
4       1961   NL    CIN      CIN   NaN     1  154     77  93   61    NaN   NaN     Y     N  710  5243  1414  247   35  158  423   761   70  33   nan   nan  653  575 3.78  46   12  40    4110  1300  147  500   829  134  124 0.98       Cincinnati Reds              Crosley Field     1117603  102  101      CIN            CIN         CIN         7257.16
...      ...  ...    ...      ...   ...   ...  ...    ...  ..  ...    ...   ...   ...   ...  ...   ...   ...  ...  ...  ...  ...   ...  ...  ..   ...   ...  ...  ...  ...  ..  ...  ..     ...   ...  ...  ...   ...  ...  ...  ...                   ...                        ...         ...  ...  ...      ...            ...         ...             ...
1021    2001   NL    SFN      SFG     W     2  162     81  90   72      N     N     N     N  799  5612  1493  304   40  235  625  1090   57  42 50.00 54.00  748  680 4.18   3    8  47    4390  1437  145  579  1080  118  170 0.98  San Francisco Giants               PacBell Park     3311958   93   92      SFG            SFN         SFN        20444.19
1022    2001   NL    SLN      STL     C     2  162     82  93   69      N     Y     N     N  814  5450  1469  274   32  199  529  1089   91  35 65.00 50.00  684  627 3.93   8   11  38    4306  1389  196  526  1083  110  156 0.98   St. Louis Cardinals           Busch Stadium II     3109578  100   99      STL            SLN         SLN        19194.93
1023    2001   AL    TBA      TBD     E     5  162     81  62  100      N     N     N     N  672  5524  1426  311   21  121  456  1116  115  52 54.00 25.00  887  781 4.94   1    6  30    4271  1513  207  569  1030  139  144 0.98  Tampa Bay Devil Rays            Tropicana Field     1298365   98  100      TBD            TBA         TBA         8014.60
1024    2001   AL    TEX      TEX     W     4  162     82  73   89      N     N     N     N  890  5685  1566  326   23  246  548  1093   97  32 75.00 55.00  968  913 5.71   4    3  37    4315  1670  222  596   951  114  167 0.98         Texas Rangers  The Ballpark at Arlington     2831021  104  105      TEX            TEX         TEX        17475.44
1025    2001   AL    TOR      TOR     E     3  162     82  80   82      N     N     N     N  767  5663  1489  287   36  195  470  1094  156  55 74.00 43.00  753  696 4.28   7   10  41    4388  1553  165  490  1041   97  184 0.98     Toronto Blue Jays                    Skydome     1915438  102  103      TOR            TOR         TOR        11823.69

[1026 rows x 49 columns]

## Exploratory Data Analysis

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1026 entries, 0 to 1025
Data columns (total 49 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   yearID          1026 non-null   int64
 1   lgID            1026 non-null   object
 2   teamID          1026 non-null   object
 3   franchID        1026 non-null   object
 4   divID           868 non-null    object
 5   Rank            1026 non-null   int64
 6   G               1026 non-null   int64
 7   Ghome           1026 non-null   int64
 8   W               1026 non-null   int64
 9   L               1026 non-null   int64
 10  DivWin          840 non-null    object
 11  WCWin           204 non-null    object
 12  LgWin           998 non-null    object
 13  WSWin           998 non-null    object
 14  R               1026 non-null   int64
 15  AB              1026 non-null   int64
 16  H               1026 non-null   int64
 17  X2B             1026 non-null   int64
 18  X3B             1026 non-null   int64
 19  HR              1026 non-null   int64
 20  BB              1026 non-null   int64
 21  SO              1026 non-null   int64
 22  SB              1026 non-null   int64
 23  CS              1026 non-null   int64
 24  HBP             844 non-null    float64
 25  SF              844 non-null    float64
 26  RA              1026 non-null   int64
 27  ER              1026 non-null   int64
 28  ERA             1026 non-null   float64
 29  CG              1026 non-null   int64
 30  SHO             1026 non-null   int64
 31  SV              1026 non-null   int64
 32  IPouts          1026 non-null   int64
 33  HA              1026 non-null   int64
 34  HRA             1026 non-null   int64
 35  BBA             1026 non-null   int64
 36  SOA             1026 non-null   int64
 37  E               1026 non-null   int64
 38  DP              1026 non-null   int64
 39  FP              1026 non-null   float64
 40  name            1026 non-null   object
 41  park            1026 non-null   object
 42  attendance      1026 non-null   int64
 43  BPF             1026 non-null   int64
 44  PPF             1026 non-null   int64
 45  teamIDBR        1026 non-null   object
 46  teamIDlahman45  1026 non-null   object
 47  teamIDretro     1026 non-null   object
 48  avg_attendance  1026 non-null   float64
dtypes: float64(5), int64(31), object(13)
memory usage: 392.9+ KB

In [5]:
df.describe()

       yearID    Rank       G   Ghome       W       L       R      AB       H     X2B     X3B      HR      BB      SO      SB      CS    HBP     SF      RA      ER     ERA      CG     SHO      SV  IPouts      HA     HRA     BBA     SOA       E      DP      FP  attendance     BPF     PPF  avg_attendance
count 1026.00 1026.00 1026.00 1026.00 1026.00 1026.00 1026.00 1026.00 1026.00 1026.00 1026.00 1026.00 1026.00 1026.00 1026.00 1026.00 844.00 844.00 1026.00 1026.00 1026.00 1026.00 1026.00 1026.00 1026.00 1026.00 1026.00 1026.00 1026.00 1026.00 1026.00 1026.00     1026.00 1026.00 1026.00         1026.00
mean  1982.37    3.76  158.52   79.26   79.18   79.18  690.00 5397.73 1394.71  239.18   35.08  135.50  522.16  897.47  103.02   52.04  36.10  46.05  690.00  617.34    3.92   26.72   10.10   35.20 4258.73 1394.71  135.50  522.16  897.47  128.94  148.01    0.98  1694421.39  100.23  100.22        10717.64
std     11.66    2.09   11.71    5.95   12.71   12.65  103.98  404.03  132.76   40.84   10.66   39.73   79.00  139.79   44.21   16.73  14.49   9.63  104.65   99.02    0.60   16.41    4.59    9.54  316.88  133.92   33.88   78.38  145.54   23.70   21.19    0.00   764115.33    4.65    4.77         4818.60
min   1961.00    1.00  103.00   44.00   37.00   40.00  329.00 3493.00  797.00  119.00   11.00   32.00  275.00  379.00   17.00   11.00   7.00  18.00  331.00  293.00    2.45    1.00    0.00   10.00 2767.00  827.00   40.00  268.00  388.00   57.00   74.00    0.97   306763.00   90.00   90.00         1893.60
25%   1973.00    2.00  161.00   81.00   71.00   71.00  628.25 5423.00 1343.00  210.25   28.00  108.00  472.25  816.00   70.00   41.00  26.00  40.00  626.00  554.00    3.49   13.00    7.00   29.00 4300.00 1340.25  112.00  475.00  807.25  113.00  135.00    0.98  1097446.50   97.00   97.00         6932.61
50%   1983.00    4.00  162.00   81.00   80.00   79.00  689.50 5498.00 1408.50  238.00   34.00  132.00  520.00  903.50   99.00   50.50  33.00  46.00  688.00  615.00    3.85   25.00   10.00   35.00 4341.00 1408.00  131.00  521.00  899.00  130.00  148.50    0.98  1589698.00  100.00  100.00        10084.64
75%   1993.00    5.00  162.00   81.00   88.00   88.00  755.00 5563.75 1475.00  268.00   41.00  161.00  573.00  986.75  131.00   61.00  43.00  52.00  754.75  679.00    4.29   39.00   13.00   42.00 4377.00 1476.00  158.00  572.00  994.00  143.00  162.00    0.98  2174151.00  103.00  103.00        13854.38
max   2001.00   10.00  165.00   84.00  116.00  120.00 1009.00 5781.00 1684.00  373.00   79.00  264.00  775.00 1399.00  341.00  123.00 100.00  77.00 1103.00 1015.00    6.38   94.00   30.00   68.00 4518.00 1734.00  241.00  784.00 1344.00  210.00  215.00    0.99  4483350.00  129.00  129.00        28047.10

In [6]:
df.columns

Index(['yearID', 'lgID', 'teamID', 'franchID', 'divID', 'Rank', 'G', 'Ghome', 'W', 'L', 'DivWin', 'WCWin', 'LgWin', 'WSWin', 'R', 'AB', 'H', 'X2B', 'X3B', 'HR', 'BB', 'SO', 'SB', 'CS', 'HBP', 'SF', 'RA', 'ER', 'ERA', 'CG', 'SHO', 'SV', 'IPouts', 'HA', 'HRA', 'BBA', 'SOA', 'E', 'DP', 'FP', 'name', 'park', 'attendance', 'BPF', 'PPF', 'teamIDBR', 'teamIDlahman45', 'teamIDretro', 'avg_attendance'], dtype='object')

In [7]:
df2 = df[:800]

In [8]:
df2

     yearID lgID teamID franchID divID  Rank    G  Ghome   W   L DivWin WCWin LgWin WSWin    R    AB     H  X2B  X3B   HR   BB    SO   SB  CS   HBP    SF   RA   ER  ERA  CG  SHO  SV  IPouts    HA  HRA  BBA  SOA    E   DP   FP               name                         park  attendance  BPF  PPF teamIDBR teamIDlahman45 teamIDretro  avg_attendance
0      1961   AL    BAL      BAL   NaN     3  163     82  95  67    NaN   NaN     N     N  691  5481  1393  227   36  149  581   902   39  30   nan   nan  588  526 3.22  54   21  33    4413  1226  109  617  926  126  173 0.98  Baltimore Orioles             Memorial Stadium      951089   96   96      BAL            BAL         BAL         5834.90
1      1961   AL    BOS      BOS   NaN     6  163     82  76  86    NaN   NaN     N     N  729  5508  1401  251   37  112  647   847   56  36   nan   nan  792  687 4.29  35    6  30    4326  1472  167  679  831  143  140 0.98     Boston Red Sox               Fenway Park II      850589  102  103      BOS            BOS         BOS         5218.34
2      1961   AL    CHA      CHW   NaN     4  163     81  86  76    NaN   NaN     N     N  765  5556  1475  216   46  138  550   612  100  40   nan   nan  726  653 4.06  39    3  33    4344  1491  158  498  814  128  138 0.98  Chicago White Sox                Comiskey Park     1146019   99   97      CHW            CHA         CHA         7030.79
3      1961   NL    CHN      CHC   NaN     7  156     78  64  90    NaN   NaN     N     N  689  5344  1364  238   51  176  539  1027   35  25   nan   nan  800  689 4.48  34    6  25    4155  1492  165  465  755  183  175 0.97       Chicago Cubs                Wrigley Field      673057  101  104      CHC            CHN         CHN         4314.47
4      1961   NL    CIN      CIN   NaN     1  154     77  93  61    NaN   NaN     Y     N  710  5243  1414  247   35  158  423   761   70  33   nan   nan  653  575 3.78  46   12  40    4110  1300  147  500  829  134  124 0.98    Cincinnati Reds                Crosley Field     1117603  102  101      CIN            CIN         CIN         7257.16
..      ...  ...    ...      ...   ...   ...  ...    ...  ..  ..    ...   ...   ...   ...  ...   ...   ...  ...  ...  ...  ...   ...  ...  ..   ...   ...  ...  ...  ...  ..  ...  ..     ...   ...  ...  ...  ...  ...  ...  ...                ...                          ...         ...  ...  ...      ...            ...         ...             ...
795    1994   AL    BAL      BAL     E     2  112     55  63  49    NaN   NaN   NaN   NaN  589  3856  1047  185   20  139  438   655   69  13 39.00 35.00  497  478 4.31  13    4  37    2993  1005  131  351  666   57  103 0.99  Baltimore Orioles  Oriole Park at Camden Yards     2535359  105  104      BAL            BAL         BAL        22637.13
796    1994   AL    BOS      BOS     E     4  115     64  54  61    NaN   NaN   NaN   NaN  552  3940  1038  222   19  120  404   723   81  38 31.00 33.00  621  564 4.93   6    3  30    3088  1104  120  450  729   81  124 0.98     Boston Red Sox               Fenway Park II     1775818  105  105      BOS            BOS         BOS        15441.90
797    1994   AL    CAL      ANA     W     4  115     63  47  68    NaN   NaN   NaN   NaN  543  3943  1042  178   16  120  402   715   65  54 27.00 29.00  660  618 5.42  11    4  21    3081  1149  150  436  682   76  110 0.98  California Angels              Anaheim Stadium     1512622  101  101      CAL            CAL         CAL        13153.23
798    1994   AL    CHA      CHW     C     1  113     53  67  46    NaN   NaN   NaN   NaN  633  3942  1133  175   39  121  497   568   77  27 20.00 46.00  498  445 3.96  13    9  20    3034   964  115  377  754   79   91 0.98  Chicago White Sox             Comiskey Park II     1697398   99   98      CHW            CHA         CHA        15021.22
799    1994   NL    CHN      CHC     C     5  113     59  49  64    NaN   NaN   NaN   NaN  500  3918  1015  189   26  109  364   750   69  53 27.00 23.00  549  508 4.47   5    5  27    3071  1054  120  392  717   81  110 0.98       Chicago Cubs                Wrigley Field     1845208   99   99      CHC            CHN         CHN        16329.27

[800 rows x 49 columns]

In [9]:
test = df[800:]

In [10]:
test

      yearID lgID teamID franchID divID  Rank    G  Ghome   W    L DivWin WCWin LgWin WSWin    R    AB     H  X2B  X3B   HR   BB    SO   SB  CS   HBP    SF   RA   ER  ERA  CG  SHO  SV  IPouts    HA  HRA  BBA   SOA    E   DP   FP                  name                       park  attendance  BPF  PPF teamIDBR teamIDlahman45 teamIDretro  avg_attendance
800     1994   NL    CIN      CIN     C     1  115     60  66   48    NaN   NaN   NaN   NaN  609  3999  1142  211   36  124  388   738  119  51 29.00 42.00  490  436 3.78   6    6  27    3115  1037  117  339   799   73   91 0.98       Cincinnati Reds         Riverfront Stadium     1897681   99   99      CIN            CIN         CIN        16501.57
801     1994   AL    CLE      CLE     C     2  113     51  66   47    NaN   NaN   NaN   NaN  679  4022  1165  240   20  167  382   629  131  48 18.00 38.00  562  494 4.36  17    5  21    3056  1097   94  404   666   90  119 0.98     Cleveland Indians               Jacobs Field     1995174   99   97      CLE            CLE         CLE        17656.41
802     1994   NL    COL      COL     W     3  117     57  53   64    NaN   NaN   NaN   NaN  573  4006  1098  206   39  125  378   761   91  53 23.00 36.00  638  590 5.15   4    5  28    3093  1185  120  448   703   84  117 0.98      Colorado Rockies          Mile High Stadium     3281511  117  118      COL            COL         COL        28047.10
803     1994   AL    DET      DET     E     5  115     58  53   62    NaN   NaN   NaN   NaN  652  3955  1048  216   25  161  520   897   46  33 34.00 48.00  671  609 5.38  15    1  20    3054  1139  148  449   560   82   90 0.98        Detroit Tigers              Tiger Stadium     1184783  101  101      DET            DET         DET        10302.46
804     1994   NL    FLO      FLA     E     5  115     59  51   64    NaN   NaN   NaN   NaN  468  3926  1043  180   24   94  349   746   65  26 40.00 30.00  576  507 4.50   5    7  30    3045  1069  120  428   649   95  111 0.98       Florida Marlins         Joe Robbie Stadium     1937467  102  103      FLA            FLO         FLO        16847.54
...      ...  ...    ...      ...   ...   ...  ...    ...  ..  ...    ...   ...   ...   ...  ...   ...   ...  ...  ...  ...  ...   ...  ...  ..   ...   ...  ...  ...  ...  ..  ...  ..     ...   ...  ...  ...   ...  ...  ...  ...                   ...                        ...         ...  ...  ...      ...            ...         ...             ...
1021    2001   NL    SFN      SFG     W     2  162     81  90   72      N     N     N     N  799  5612  1493  304   40  235  625  1090   57  42 50.00 54.00  748  680 4.18   3    8  47    4390  1437  145  579  1080  118  170 0.98  San Francisco Giants               PacBell Park     3311958   93   92      SFG            SFN         SFN        20444.19
1022    2001   NL    SLN      STL     C     2  162     82  93   69      N     Y     N     N  814  5450  1469  274   32  199  529  1089   91  35 65.00 50.00  684  627 3.93   8   11  38    4306  1389  196  526  1083  110  156 0.98   St. Louis Cardinals           Busch Stadium II     3109578  100   99      STL            SLN         SLN        19194.93
1023    2001   AL    TBA      TBD     E     5  162     81  62  100      N     N     N     N  672  5524  1426  311   21  121  456  1116  115  52 54.00 25.00  887  781 4.94   1    6  30    4271  1513  207  569  1030  139  144 0.98  Tampa Bay Devil Rays            Tropicana Field     1298365   98  100      TBD            TBA         TBA         8014.60
1024    2001   AL    TEX      TEX     W     4  162     82  73   89      N     N     N     N  890  5685  1566  326   23  246  548  1093   97  32 75.00 55.00  968  913 5.71   4    3  37    4315  1670  222  596   951  114  167 0.98         Texas Rangers  The Ballpark at Arlington     2831021  104  105      TEX            TEX         TEX        17475.44
1025    2001   AL    TOR      TOR     E     3  162     82  80   82      N     N     N     N  767  5663  1489  287   36  195  470  1094  156  55 74.00 43.00  753  696 4.28   7   10  41    4388  1553  165  490  1041   97  184 0.98     Toronto Blue Jays                    Skydome     1915438  102  103      TOR            TOR         TOR        11823.69

[226 rows x 49 columns]

In [11]:
test2 = test

## Regression Analysis

In [12]:
df2.columns

Index(['yearID', 'lgID', 'teamID', 'franchID', 'divID', 'Rank', 'G', 'Ghome', 'W', 'L', 'DivWin', 'WCWin', 'LgWin', 'WSWin', 'R', 'AB', 'H', 'X2B', 'X3B', 'HR', 'BB', 'SO', 'SB', 'CS', 'HBP', 'SF', 'RA', 'ER', 'ERA', 'CG', 'SHO', 'SV', 'IPouts', 'HA', 'HRA', 'BBA', 'SOA', 'E', 'DP', 'FP', 'name', 'park', 'attendance', 'BPF', 'PPF', 'teamIDBR', 'teamIDlahman45', 'teamIDretro', 'avg_attendance'], dtype='object')

In [13]:
# Use runs (R) per game to predict average attendance.
# For every 1 run scored per game, attendance increases by how much?

In [14]:
y = df2['avg_attendance']
X = df2['R']

In [15]:
X = sm.add_constant(X)

In [16]:
model = sm.OLS(y,X).fit()

In [17]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:         avg_attendance   R-squared:                       0.103
Model:                            OLS   Adj. R-squared:                  0.102
Method:                 Least Squares   F-statistic:                     91.84
Date:                Sat, 03 Apr 2021   Prob (F-statistic):           1.16e-20
Time:                        20:01:07   Log-Likelihood:                -7792.8
No. Observations:                 800   AIC:                         1.559e+04
Df Residuals:                     798   BIC:                         1.560e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -374.5554   1065.764     -0.351      0.725   -2466.588    1717.477
R             15.1181      1.578      9.583      0.000      12.021      18.215
==============================================================================
Omnibus:                       88.632   Durbin-Watson:                   1.361
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              118.021
Skew:                           0.862   Prob(JB):                     2.36e-26
Kurtosis:                       3.755   Cond. No.                     4.94e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.94e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [18]:
# Use home runs (HR) per game to predict average attendance.
# For every 1 home run hit per game, attendance increases by how much?

In [19]:
y = df2['avg_attendance']
X = df2['HR']

In [20]:
X = sm.add_constant(X)

In [21]:
model2 = sm.OLS(y,X).fit()

In [22]:
model2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:         avg_attendance   R-squared:                       0.035
Model:                            OLS   Adj. R-squared:                  0.034
Method:                 Least Squares   F-statistic:                     29.14
Date:                Sat, 03 Apr 2021   Prob (F-statistic):           8.90e-08
Time:                        20:01:07   Log-Likelihood:                -7822.1
No. Observations:                 800   AIC:                         1.565e+04
Df Residuals:                     798   BIC:                         1.566e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       6778.9795    569.528     11.903      0.000    5661.029    7896.930
HR            23.4693      4.348      5.398      0.000      14.935      32.004
==============================================================================
Omnibus:                       68.560   Durbin-Watson:                   1.334
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               84.243
Skew:                           0.767   Prob(JB):                     5.09e-19
Kurtosis:                       3.420   Cond. No.                         494.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [23]:
# Use number of wins to predict attendance; do not normalize for number of games.
# For every game won in a season, how much does average attendance increase?

In [24]:
y = df2['avg_attendance']
X = df2['W']

In [25]:
X = sm.add_constant(X)

In [26]:
model3 = sm.OLS(y,X).fit()

In [27]:
model3.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:         avg_attendance   R-squared:                       0.141
Model:                            OLS   Adj. R-squared:                  0.140
Method:                 Least Squares   F-statistic:                     131.1
Date:                Sat, 03 Apr 2021   Prob (F-statistic):           3.28e-28
Time:                        20:01:07   Log-Likelihood:                -7775.6
No. Observations:                 800   AIC:                         1.556e+04
Df Residuals:                     798   BIC:                         1.556e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -629.1012    917.050     -0.686      0.493   -2429.217    1171.015
W            130.2004     11.372     11.450      0.000     107.879     152.522
==============================================================================
Omnibus:                       95.178   Durbin-Watson:                   1.186
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              134.102
Skew:                           0.867   Prob(JB):                     7.59e-30
Kurtosis:                       4.008   Cond. No.                         519.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [28]:
# Suppose a team won zero games in a season.
# Predict the average attendance.

In [29]:
zero = pd.DataFrame(data={'W':[0,0]})

In [30]:
zero

   W
0  0
1  0

In [31]:
zero.shape

(2, 1)

In [32]:
#model3.predict(zero)

In [33]:
#prediction = model.predict(tevst)

In [34]:
# Use year to predict average attendance.
# How much does average attendance increase each year?

In [35]:
y = df2['avg_attendance']
X = df2['yearID']

In [36]:
X = sm.add_constant(X)

In [37]:
model4 = sm.OLS(y,X).fit()

In [38]:
model4.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:         avg_attendance   R-squared:                       0.324
Model:                            OLS   Adj. R-squared:                  0.323
Method:                 Least Squares   F-statistic:                     382.8
Date:                Sat, 03 Apr 2021   Prob (F-statistic):           6.16e-70
Time:                        20:01:07   Log-Likelihood:                -7679.7
No. Observations:                 800   AIC:                         1.536e+04
Df Residuals:                     798   BIC:                         1.537e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -5.115e+05   2.66e+04    -19.200      0.000   -5.64e+05   -4.59e+05
yearID       263.5118     13.468     19.566      0.000     237.076     289.948
==============================================================================
Omnibus:                       58.537   Durbin-Watson:                   1.974
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               70.742
Skew:                           0.668   Prob(JB):                     4.35e-16
Kurtosis:                       3.580   Cond. No.                     4.17e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.17e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [39]:
# Game wins, runs per game and home runs per game are positively correlated with attendance.
# We saw in the course material that runs per game and home runs per game are correlated
# with each other. Are wins and runs per game or wins and home runs per game correlated?

In [40]:
# What is the correlation coefficient for wins and runs per game?

In [41]:
df2[["W","R"]].corr()

     W    R
W 1.00 0.67
R 0.67 1.00

In [42]:
# What is the correlation coefficient for wins and home runs per game?

In [43]:
df2[["W","HR"]].corr()

      W   HR
W  1.00 0.41
HR 0.41 1.00

In [44]:
# Stratify Teams_small by wins: divide number of wins by 10 and then round to the nearest
# integer. Keep only strata 5 through 10, which have 20 or more data points.

In [45]:
# How many observations are in the 8 win strata?

In [46]:
# Calculate the slope of the regression line predicting average attendance given
# runs per game for each of the win strata. Which win stratum has the largest
# regression line slope?

In [47]:
# Calculate the slope of the regression line predicting average attendance given
# HR per game for each of the win strata. Which win stratum has the largest
# regression line slope?

In [48]:
# Fit a multivariate regression determining the effects of runs per game,
# home runs per game, wins, and year on average attendance. Use the original
# Teams_small wins column, not the win strata from question 3.

In [49]:
df.head()

   yearID lgID teamID franchID divID  Rank    G  Ghome   W   L DivWin WCWin LgWin WSWin    R    AB     H  X2B  X3B   HR   BB    SO   SB  CS  HBP  SF   RA   ER  ERA  CG  SHO  SV  IPouts    HA  HRA  BBA  SOA    E   DP   FP               name              park  attendance  BPF  PPF teamIDBR teamIDlahman45 teamIDretro  avg_attendance
0    1961   AL    BAL      BAL   NaN     3  163     82  95  67    NaN   NaN     N     N  691  5481  1393  227   36  149  581   902   39  30  nan nan  588  526 3.22  54   21  33    4413  1226  109  617  926  126  173 0.98  Baltimore Orioles  Memorial Stadium      951089   96   96      BAL            BAL         BAL         5834.90
1    1961   AL    BOS      BOS   NaN     6  163     82  76  86    NaN   NaN     N     N  729  5508  1401  251   37  112  647   847   56  36  nan nan  792  687 4.29  35    6  30    4326  1472  167  679  831  143  140 0.98     Boston Red Sox    Fenway Park II      850589  102  103      BOS            BOS         BOS         5218.34
2    1961   AL    CHA      CHW   NaN     4  163     81  86  76    NaN   NaN     N     N  765  5556  1475  216   46  138  550   612  100  40  nan nan  726  653 4.06  39    3  33    4344  1491  158  498  814  128  138 0.98  Chicago White Sox     Comiskey Park     1146019   99   97      CHW            CHA         CHA         7030.79
3    1961   NL    CHN      CHC   NaN     7  156     78  64  90    NaN   NaN     N     N  689  5344  1364  238   51  176  539  1027   35  25  nan nan  800  689 4.48  34    6  25    4155  1492  165  465  755  183  175 0.97       Chicago Cubs     Wrigley Field      673057  101  104      CHC            CHN         CHN         4314.47
4    1961   NL    CIN      CIN   NaN     1  154     77  93  61    NaN   NaN     Y     N  710  5243  1414  247   35  158  423   761   70  33  nan nan  653  575 3.78  46   12  40    4110  1300  147  500  829  134  124 0.98    Cincinnati Reds     Crosley Field     1117603  102  101      CIN            CIN         CIN         7257.16

In [50]:
y = df2['avg_attendance']
X = df2[["R","HR","W",'yearID']]

In [51]:
X = sm.add_constant(X)

In [52]:
model5 = sm.OLS(y,X).fit()

In [53]:
model5.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:         avg_attendance   R-squared:                       0.487
Model:                            OLS   Adj. R-squared:                  0.485
Method:                 Least Squares   F-statistic:                     188.9
Date:                Sat, 03 Apr 2021   Prob (F-statistic):          9.23e-114
Time:                        20:01:07   Log-Likelihood:                -7569.2
No. Observations:                 800   AIC:                         1.515e+04
Df Residuals:                     795   BIC:                         1.517e+04
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -5.555e+05   2.42e+04    -22.920      0.000   -6.03e+05   -5.08e+05
R             -6.8689      2.152     -3.192      0.001     -11.093      -2.645
HR            12.9722      4.551      2.850      0.004       4.039      21.906
W            155.9905     12.113     12.878      0.000     132.213     179.768
yearID       280.9467     12.307     22.829      0.000     256.789     305.104
==============================================================================
Omnibus:                      109.954   Durbin-Watson:                   1.982
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              178.787
Skew:                           0.894   Prob(JB):                     1.50e-39
Kurtosis:                       4.472   Cond. No.                     4.60e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.6e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [54]:
# Use your model from Question 4 to predict average attendance for teams in 2002
# in the original Teams data frame.

#### Python code done by Dennis Lam